### ISSUE TITLE
malformed JSON scenarios send a correct JSON format payload

### ISSUE THREAD

**Issue by CarmenCirebea** [Endava/cats#3]
The "Send a malformed JSON" scenario doesn't work as expected: the "bla" string that needed to be appended to the payload isn't.

Expected: send a payload + "bla" string at final and receive a 4XX response code
Actual: sends a correct payload and receives a 200 response code

![MalformedJSON](https://user-images.githubusercontent.com/23148631/100338675-904c5200-2fe1-11eb-829e-fd407be4f0a2.png)

**Comment by en-milie** [comment]
CATS is actually sending the malformed JSON, but due to the way it creates the reports it can only incorporate. In order to make this more visible, the following updates were made:
- Add a section in README.md with details about the [MalformedJsonFuzzer](https://github.com/Endava/cats#malformedjsonfuzzer)
- Add a new log line saying `Final payload:` before doing the service call to check the exact payload that is being sent to the service
- The report will contain the following `Scenario` string for `MalformedJsonFuzeer`: `Scenario: Send a malformed JSON which has the string 'bla' at the end (the report won't actually display it as all requests need to be actual JSONs, but please check the logs to see the actual request payload)`
